import XCTest
@testable import DavidNookCore

/// 元件 3：ClipboardPolicy（該不該記錄、記錄成哪一種）。
final class ClipboardPolicyTests: XCTestCase {
    private let policy = ClipboardPolicy()

    private func decision(_ entries: [String: Data], policy: ClipboardPolicy? = nil, paused: Bool = false, source: String? = nil) -> ClipboardDecision {
        (policy ?? self.policy).evaluate(makeSnapshot(entries, source: source), isPaused: paused)
    }

    // MARK: 常數與預設值

    func testPasteboardTypeConstantsAreLockedToExactStrings() {
        XCTAssertEqual(PBType.concealed, "org.nspasteboard.ConcealedType")
        XCTAssertEqual(PBType.transient, "org.nspasteboard.TransientType")
        XCTAssertEqual(PBType.autoGenerated, "org.nspasteboard.AutoGeneratedType")
        XCTAssertEqual(PBType.onePassword, "com.agilebits.onepassword")
        XCTAssertEqual(PBType.petermaurerTransient, "de.petermaurer.TransientPasteboardType")
        XCTAssertEqual(PBType.selfMarker, "io.github.davidkong3804.DavidNook.self")
        XCTAssertEqual(PBType.source, "org.nspasteboard.source")
        XCTAssertEqual(PBType.fileURL, "public.file-url")
        XCTAssertEqual(PBType.png, "public.png")
        XCTAssertEqual(PBType.tiff, "public.tiff")
        XCTAssertEqual(PBType.utf8Text, "public.utf8-plain-text")
        XCTAssertEqual(PBType.defaultIgnored, [
            "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
        ])
    }

    func testDefaultLimitsAre1MBTextAnd20MBImage() {
        XCTAssertEqual(policy.maxTextBytes, 1_048_576)
        XCTAssertEqual(policy.maxImageBytes, 20 * 1_048_576)
    }

    // MARK: 隱私型別

    func testConcealedTransientAndAutoGeneratedAreEachSkippedEvenWithPlainText() {
        for type in [PBType.concealed, PBType.transient, PBType.autoGenerated] {
            let result = decision([PBType.utf8Text: utf8("hunter2"), type: Data()])
            XCTAssertEqual(result, .skip(.sensitiveType), "\(type) 必須被略過")
        }
    }

    func testLegacyPasswordManagerMarkersAreSkipped() {
        for type in [PBType.onePassword, PBType.petermaurerTransient] {
            XCTAssertEqual(decision([PBType.utf8Text: utf8("secret"), type: Data()]), .skip(.sensitiveType), type)
        }
    }

    func testSensitiveSnapshotNeverReadsAnyData() {
        for type in PBType.defaultIgnored {
            let counter = DataReadCounter()
            let snapshot = makeCountingSnapshot([PBType.utf8Text: utf8("pw"), PBType.png: tinyPNG, type: utf8("x")], counter: counter)
            XCTAssertEqual(policy.evaluate(snapshot), .skip(.sensitiveType))
            XCTAssertEqual(counter.count, 0, "\(type)：被略過的剪貼簿內容不可被讀取")
        }
    }

    func testSensitiveTypeMatchIsCaseInsensitive() {
        XCTAssertEqual(decision([PBType.utf8Text: utf8("x"), "ORG.NSPASTEBOARD.CONCEALEDTYPE": Data()]), .skip(.sensitiveType))
    }

    func testSensitiveTypeBeatsSelfMarker() {
        XCTAssertEqual(decision([PBType.concealed: Data(), PBType.selfMarker: utf8(UUID().uuidString)]), .skip(.sensitiveType))
    }

    func testCustomIgnoredTypesAreHonoured() {
        var custom = ClipboardPolicy()
        custom.ignoredTypes.insert("com.example.vault")
        XCTAssertEqual(decision([PBType.utf8Text: utf8("x"), "com.example.vault": Data()], policy: custom), .skip(.sensitiveType))
        XCTAssertNotEqual(decision([PBType.utf8Text: utf8("x"), "com.example.vault": Data()]), .skip(.sensitiveType))
    }

    // MARK: 文字

    func testPlainTextIsRecordedWithSourceApp() {
        let result = decision([PBType.utf8Text: utf8("你好 world")], source: "com.apple.Notes")
        XCTAssertEqual(result, .record(ClipboardCapture(text: "你好 world", sourceAppBundleID: "com.apple.Notes")))
    }

    func testEmptyAndWhitespaceOnlyTextIsSkipped() {
        for text in ["", " ", "  \n\t  ", "\n\n"] {
            XCTAssertEqual(decision([PBType.utf8Text: utf8(text)]), .skip(.empty), "「\(text)」")
        }
    }

    func testTextWithSurroundingWhitespaceIsKeptVerbatim() {
        let result = decision([PBType.utf8Text: utf8("  keep me \n")])
        XCTAssertEqual(result, .record(ClipboardCapture(text: "  keep me \n")))
    }

    func testInvalidUTF8TextIsSkippedAsUnsupported() {
        XCTAssertEqual(decision([PBType.utf8Text: Data([0xFF, 0xFE, 0xFD])]), .skip(.unsupported))
    }

    func testTextSizeLimitBoundary() {
        let small = ClipboardPolicy(maxTextBytes: 10)
        XCTAssertEqual(decision([PBType.utf8Text: utf8(String(repeating: "a", count: 10))], policy: small),
                       .record(ClipboardCapture(text: String(repeating: "a", count: 10))), "剛好等於上限要記錄")
        XCTAssertEqual(decision([PBType.utf8Text: utf8(String(repeating: "a", count: 11))], policy: small), .skip(.tooLarge))
    }

    func testTextLimitIsMeasuredInBytesNotCharacters() {
        let small = ClipboardPolicy(maxTextBytes: 6)
        XCTAssertNotEqual(decision([PBType.utf8Text: utf8("繁體")], policy: small), .skip(.tooLarge), "2 字 = 6 bytes")
        XCTAssertEqual(decision([PBType.utf8Text: utf8("繁體字")], policy: small), .skip(.tooLarge), "3 字 = 9 bytes")
    }

    // MARK: 圖片

    func testImageIsRecordedAsPNGOrTIFFAndPNGIsPreferred() {
        XCTAssertEqual(decision([PBType.png: tinyPNG]), .record(ClipboardCapture(imageData: tinyPNG, fileExtension: "png")))
        let tiffBytes = utf8("fake-tiff")
        XCTAssertEqual(decision([PBType.tiff: tiffBytes]), .record(ClipboardCapture(imageData: tiffBytes, fileExtension: "tiff")))
        XCTAssertEqual(decision([PBType.tiff: tiffBytes, PBType.png: tinyPNG]),
                       .record(ClipboardCapture(imageData: tinyPNG, fileExtension: "png")), "兩種都有時用 PNG")
    }

    func testImageSizeLimitBoundary() {
        let small = ClipboardPolicy(maxImageBytes: 8)
        XCTAssertEqual(decision([PBType.png: Data(count: 8)], policy: small), .record(ClipboardCapture(imageData: Data(count: 8), fileExtension: "png")))
        XCTAssertEqual(decision([PBType.png: Data(count: 9)], policy: small), .skip(.tooLarge))
    }

    func testEmptyImageDataIsSkipped() {
        XCTAssertEqual(decision([PBType.png: Data()]), .skip(.empty))
    }

    // MARK: 檔案

    func testSingleAndMultipleFileURLsAreRecordedAsFiles() {
        let single = policy.evaluate(PasteboardSnapshot(changeCount: 1, types: [PBType.fileURL], data: [PBType.fileURL: [fileURLData("/Users/me/a.txt")]]))
        XCTAssertEqual(single, .record(ClipboardCapture(filePaths: ["/Users/me/a.txt"])))

        let multi = policy.evaluate(PasteboardSnapshot(changeCount: 1, types: [PBType.fileURL],
                                                       data: [PBType.fileURL: [fileURLData("/Users/me/a.txt"), fileURLData("/Users/me/b.txt")]]))
        XCTAssertEqual(multi, .record(ClipboardCapture(filePaths: ["/Users/me/a.txt", "/Users/me/b.txt"])))
    }

    func testPercentEncodedFileURLIsDecodedToPlainPath() {
        let result = decision([PBType.fileURL: utf8("file:///Users/me/My%20File%20%E4%B8%AD%E6%96%87.txt")])
        XCTAssertEqual(result, .record(ClipboardCapture(filePaths: ["/Users/me/My File 中文.txt"])))
    }

    func testNonFileURLsAreIgnoredAndFallBackToTextWhenNoValidFilePath() {
        let result = decision([PBType.fileURL: utf8("https://example.com/a"), PBType.utf8Text: utf8("fallback")])
        XCTAssertEqual(result, .record(ClipboardCapture(text: "fallback")))
        XCTAssertEqual(decision([PBType.fileURL: utf8("not a url at all ???")]), .skip(.unsupported))
    }

    // MARK: 優先序：files > image > text

    /// 從 Finder 複製檔案時，剪貼簿同時帶有「檔名文字」與「檔案圖示圖片」；
    /// 若 text/image 優先，會把檔案誤記成一段檔名或一張圖示。因此 files 最優先，其次 image
    /// （從瀏覽器複製圖片常同時帶有網址文字，使用者要的是圖片），最後才是 text。
    func testPriorityFilesOverImageOverText() {
        let finderLike: [String: Data] = [
            PBType.fileURL: fileURLData("/Users/me/report.pdf"),
            PBType.png: tinyPNG,
            PBType.tiff: utf8("icon"),
            PBType.utf8Text: utf8("report.pdf"),
        ]
        XCTAssertEqual(decision(finderLike), .record(ClipboardCapture(filePaths: ["/Users/me/report.pdf"])))

        let browserImage: [String: Data] = [PBType.png: tinyPNG, PBType.utf8Text: utf8("https://example.com/cat.png")]
        XCTAssertEqual(decision(browserImage), .record(ClipboardCapture(imageData: tinyPNG, fileExtension: "png")))

        XCTAssertEqual(decision([PBType.utf8Text: utf8("only text")]), .record(ClipboardCapture(text: "only text")))
    }

    func testOversizedImageDoesNotFallBackToTextSilently() {
        let small = ClipboardPolicy(maxImageBytes: 4)
        XCTAssertEqual(decision([PBType.png: Data(count: 100), PBType.utf8Text: utf8("caption")], policy: small), .skip(.tooLarge))
    }

    // MARK: 暫停、自己寫的、不支援

    func testPausedSkipsWithoutReadingAnyData() {
        let counter = DataReadCounter()
        let snapshot = makeCountingSnapshot([PBType.utf8Text: utf8("x")], counter: counter)
        XCTAssertEqual(policy.evaluate(snapshot, isPaused: true), .skip(.paused))
        XCTAssertEqual(counter.count, 0)
    }

    func testSelfMarkerIsOwnWriteCarryingItemIDAndNeverRecorded() {
        let id = UUID()
        let result = decision([PBType.utf8Text: utf8("clicked item"), PBType.selfMarker: utf8(id.uuidString)])
        XCTAssertEqual(result, .ownWrite(itemID: id))
        XCTAssertEqual(decision([PBType.utf8Text: utf8("x"), PBType.selfMarker: utf8("not-a-uuid")]), .ownWrite(itemID: nil))
        XCTAssertEqual(decision([PBType.utf8Text: utf8("x"), PBType.selfMarker: Data()]), .ownWrite(itemID: nil))
    }

    func testOwnWriteOnlyReadsTheMarkerNotTheContent() {
        let counter = DataReadCounter()
        let snapshot = makeCountingSnapshot([PBType.utf8Text: utf8("content"), PBType.selfMarker: utf8(UUID().uuidString)], counter: counter)
        _ = policy.evaluate(snapshot)
        XCTAssertEqual(counter.readTypes, [PBType.selfMarker])
    }

    func testUnsupportedOrEmptyTypeListIsSkipped() {
        XCTAssertEqual(decision(["public.rtf": utf8("{\\rtf1}")]), .skip(.unsupported))
        XCTAssertEqual(decision([:]), .skip(.unsupported))
    }
}
