import AppKit
import XCTest
@testable import DavidNookCore

/// 元件 7：以「真實 NSPasteboard」做整合測試。
/// 只使用 NamedPasteboardTestCase 建立的具名剪貼簿（每個測試一個獨立名稱，tearDown 釋放），不碰系統剪貼簿。
final class ClipboardPasteboardIntegrationTests: NamedPasteboardTestCase {
    /// 包住真實 reader，計算 snapshot() 被呼叫的次數。
    private final class CountingReader: PasteboardReading, @unchecked Sendable {
        let inner: NSPasteboardReader
        private let lock = NSLock()
        private var calls = 0
        init(_ inner: NSPasteboardReader) { self.inner = inner }
        var snapshotCalls: Int { lock.withLock { calls } }
        var changeCount: Int { inner.changeCount }
        func snapshot() -> PasteboardSnapshot {
            lock.withLock { calls += 1 }
            return inner.snapshot()
        }
    }

    private struct Rig {
        let monitor: ClipboardMonitor
        let store: ClipboardStore
        let reader: CountingReader
    }

    private func makeRig(scheduler: ClipboardScheduler = ManualClipboardScheduler(), interval: TimeInterval = 0.5) -> Rig {
        let reader = CountingReader(NSPasteboardReader(pasteboard: pasteboard, sourceAppProvider: { "com.example.frontmost" }))
        let store = ClipboardStore(persistence: InMemoryClipboardPersistence())
        let monitor = ClipboardMonitor(reader: reader, store: store, scheduler: scheduler, interval: interval)
        return Rig(monitor: monitor, store: store, reader: reader)
    }

    private func bytes(_ string: String) -> Data { Data(string.utf8) }

    private func firstItem(_ store: ClipboardStore) async throws -> ClipboardItem {
        let items = await store.items
        return try XCTUnwrap(items.first)
    }

    // MARK: 隱私型別

    func testConcealedTextOnRealPasteboardIsNotRecorded() async {
        let rig = makeRig()
        await rig.monitor.start()
        externalCopy([(PBType.utf8Text, bytes("hunter2")), (PBType.concealed, bytes("1"))])
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        XCTAssertTrue(items.isEmpty)
    }

    func testConcealedMarkerWithEmptyDataIsStillDetectedOnRealPasteboard() async {
        // 許多密碼管理員只宣告型別、資料為空；NSPasteboard 必須仍然把這個型別列出來。
        let rig = makeRig()
        await rig.monitor.start()
        externalCopy([(PBType.utf8Text, bytes("hunter2")), (PBType.concealed, Data())])
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        XCTAssertTrue(items.isEmpty)
    }

    func testTransientAutoGeneratedAndLegacyMarkersAreNotRecordedOnRealPasteboard() async {
        let rig = makeRig()
        await rig.monitor.start()
        let markers = [
            PBType.transient, PBType.autoGenerated, PBType.onePassword, PBType.petermaurerTransient,
            PBType.typeIt4MeClipping,
        ]
        for (i, type) in markers.enumerated() {
            externalCopy([(PBType.utf8Text, bytes("secret-\(i)")), (type, bytes("1"))])
            await rig.monitor.pollOnce(now: t(Double(i)))
        }
        let items = await rig.store.items
        XCTAssertEqual(items.compactMap(\.text), [], "不得有任何標記型別的內容被記錄（測試資料為自編字串）")
    }

    /// Typinator 的標記 "Pasteboard generator type" 不是合法的 UTI（含空白）。實測（具名剪貼簿）：
    /// 用 `NSPasteboardItem.setData` 寫入時型別會直接消失；用舊式 `declareTypes`／`setData(forType:)` 寫入時，
    /// `NSPasteboard.types` 會同時列出原字串與一個 `dyn.` 動態 UTI。reader 收集了 `pasteboard.types`，所以舊式寫法可被偵測。
    func testTypinatorLegacyMarkerDeclaredTheOldWayIsNotRecordedOnRealPasteboard() async {
        let rig = makeRig()
        await rig.monitor.start()
        let marker = NSPasteboard.PasteboardType(PBType.typinatorGenerator)
        pasteboard.clearContents()
        pasteboard.declareTypes([.string, marker], owner: nil)
        pasteboard.setString("secret-typinator", forType: .string)
        pasteboard.setData(bytes("1"), forType: marker)
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        XCTAssertEqual(items.compactMap(\.text), [], "Typinator 的 generator 標記必須被略過")
    }

    // MARK: reader 層：被略過的快照不讀內容（F7a）

    /// 讓 reader 把「每次真的向 NSPasteboard 讀資料」回報給計數器，證明敏感快照在 reader 層就沒有讀任何資料。
    private func makeObservedReader(_ counter: DataReadCounter) -> NSPasteboardReader {
        NSPasteboardReader(
            pasteboard: pasteboard,
            sourceAppProvider: { "com.example.frontmost" },
            dataReadObserver: { counter.record($0) }
        )
    }

    func testControlRecordingPlainTextDoesReadDataSoTheReaderCounterIsNotVacuous() {
        let counter = DataReadCounter()
        let reader = makeObservedReader(counter)
        externalCopy([(PBType.utf8Text, bytes("plain text"))])
        let decision = ClipboardPolicy().evaluate(reader.snapshot())
        XCTAssertEqual(decision, .record(ClipboardCapture(text: "plain text", sourceAppBundleID: "com.example.frontmost")))
        XCTAssertTrue(counter.readTypes.contains(PBType.utf8Text), "對照組：要記錄的內容一定會讀資料；實際讀了 \(counter.readTypes)")
    }

    func testSensitiveSnapshotsReadNoPasteboardDataAtTheReaderLayer() {
        let counter = DataReadCounter()
        let reader = makeObservedReader(counter)
        let policy = ClipboardPolicy()
        // item.setData 寫得進去的標記型別（Typinator 的型別含空白，另測舊式寫法）
        for marker in PBType.defaultIgnored where marker != PBType.typinatorGenerator {
            externalCopy([(PBType.utf8Text, bytes("secret")), (PBType.png, tinyPNG), (PBType.fileURL, bytes("file:///secret")), (marker, bytes("1"))])
            XCTAssertEqual(policy.evaluate(reader.snapshot()), .skip(.sensitiveType), marker)
            XCTAssertEqual(counter.readTypes, [], "\(marker)：敏感快照在 reader 層不得讀取任何資料")
        }

        let typinator = NSPasteboard.PasteboardType(PBType.typinatorGenerator)
        pasteboard.clearContents()
        pasteboard.declareTypes([.string, typinator], owner: nil)
        pasteboard.setString("secret", forType: .string)
        pasteboard.setData(bytes("1"), forType: typinator)
        XCTAssertEqual(policy.evaluate(reader.snapshot()), .skip(.sensitiveType))
        XCTAssertEqual(counter.readTypes, [], "Typinator 標記：同樣不得讀取任何資料")
    }

    func testMonitorPollingASensitiveCopyReadsNoPasteboardDataAtTheReaderLayer() async {
        let counter = DataReadCounter()
        let store = ClipboardStore(persistence: InMemoryClipboardPersistence())
        let monitor = ClipboardMonitor(reader: makeObservedReader(counter), store: store, scheduler: ManualClipboardScheduler())
        await monitor.start()
        externalCopy([(PBType.utf8Text, bytes("hunter2")), (PBType.concealed, Data())])
        await monitor.pollOnce(now: t(1))
        let items = await store.items
        XCTAssertTrue(items.isEmpty)
        XCTAssertEqual(counter.readTypes, [], "monitor 輪詢到機密複製時，reader 一個位元組都不能讀")
    }

    // MARK: 一般內容

    func testPlainTextOnRealPasteboardIsRecordedWithSourceApp() async {
        let rig = makeRig()
        await rig.monitor.start()
        externalCopy([(PBType.utf8Text, bytes("你好，世界"))])
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        XCTAssertEqual(items.count, 1)
        XCTAssertEqual(items.first?.kind, .text)
        XCTAssertEqual(items.first?.text, "你好，世界")
        XCTAssertEqual(items.first?.sourceAppBundleID, "com.example.frontmost")
    }

    func testStringWrittenThroughNSPasteboardAPIIsRecorded() async {
        let rig = makeRig()
        await rig.monitor.start()
        pasteboard.clearContents()
        pasteboard.setString("via setString", forType: .string)
        await rig.monitor.pollOnce(now: t(1))
        let order = await rig.store.items.compactMap(\.text)
        XCTAssertEqual(order, ["via setString"])
    }

    func testFileURLOnRealPasteboardIsRecordedAsFiles() async {
        let rig = makeRig()
        await rig.monitor.start()
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([NSURL(fileURLWithPath: "/Users/example/Documents/report final.pdf")]))
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        XCTAssertEqual(items.count, 1)
        XCTAssertEqual(items.first?.kind, .files)
        XCTAssertEqual(items.first?.filePaths, ["/Users/example/Documents/report final.pdf"])
    }

    func testMultipleFileURLsOnRealPasteboardAreRecordedAsOneFilesItem() async {
        let rig = makeRig()
        await rig.monitor.start()
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([NSURL(fileURLWithPath: "/Users/example/a.txt"), NSURL(fileURLWithPath: "/Users/example/b.txt")]))
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        XCTAssertEqual(items.count, 1)
        XCTAssertEqual(items.first?.filePaths, ["/Users/example/a.txt", "/Users/example/b.txt"])
    }

    func testPNGOnRealPasteboardIsRecordedAsImageAndReadableBack() async throws {
        let rig = makeRig()
        await rig.monitor.start()
        externalCopy([(PBType.png, tinyPNG)])
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        let item = try XCTUnwrap(items.first)
        XCTAssertEqual(item.kind, .image)
        XCTAssertTrue(try XCTUnwrap(item.imageFileName).hasSuffix(".png"))
        let data = await rig.store.imageData(for: item)
        XCTAssertEqual(data, tinyPNG)
    }

    func testTIFFOnRealPasteboardIsRecordedAsImage() async throws {
        let rig = makeRig()
        await rig.monitor.start()
        let tiff = try XCTUnwrap(NSImage(data: tinyPNG)?.tiffRepresentation)
        externalCopy([(PBType.tiff, tiff)])
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        let item = try XCTUnwrap(items.first)
        XCTAssertEqual(item.kind, .image)
        XCTAssertTrue(try XCTUnwrap(item.imageFileName).hasSuffix(".tiff"))
    }

    func testFinderStyleCopyWithFileTextAndIconIsRecordedAsFilesNotImageOrText() async throws {
        let rig = makeRig()
        await rig.monitor.start()
        let icon = try XCTUnwrap(NSImage(data: tinyPNG)?.tiffRepresentation)
        externalCopy([
            (PBType.fileURL, fileURLData("/Users/example/report.pdf")),
            (PBType.tiff, icon),
            (PBType.utf8Text, bytes("report.pdf")),
        ])
        await rig.monitor.pollOnce(now: t(1))
        let items = await rig.store.items
        XCTAssertEqual(items.map(\.kind), [.files])
        XCTAssertEqual(items.first?.filePaths, ["/Users/example/report.pdf"])
    }

    // MARK: 輪詢行為

    func testPollingOnlyReadsContentWhenChangeCountChanged() async {
        let rig = makeRig()
        await rig.monitor.start()
        for i in 0..<5 { await rig.monitor.pollOnce(now: t(Double(i))) }
        XCTAssertEqual(rig.reader.snapshotCalls, 0)
        externalCopy([(PBType.utf8Text, bytes("changed"))])
        for i in 5..<10 { await rig.monitor.pollOnce(now: t(Double(i))) }
        XCTAssertEqual(rig.reader.snapshotCalls, 1)
    }

    func testRealTimerEndToEndRecordsNewCopyWithinAFewTicks() async throws {
        let rig = makeRig(scheduler: TaskClipboardScheduler(), interval: 0.02)
        await rig.monitor.start()
        externalCopy([(PBType.utf8Text, bytes("end to end"))])
        var recorded: [String] = []
        for _ in 0..<250 where recorded.isEmpty {
            try await Task.sleep(nanoseconds: 20_000_000)
            recorded = await rig.store.items.compactMap(\.text)
        }
        await rig.monitor.stop()
        XCTAssertEqual(recorded, ["end to end"])
    }

    // MARK: 寫回

    func testWriteBackTextRoundTripsAndIsNotRecordedAgain() async throws {
        let rig = makeRig()
        await rig.monitor.start()
        externalCopy([(PBType.utf8Text, bytes("original"))])
        await rig.monitor.pollOnce(now: t(1))
        let item = try await firstItem(rig.store)

        // 使用者在別處複製了其他東西，之後從歷史點選「original」貼回
        externalCopy([(PBType.utf8Text, bytes("something else"))])
        await rig.monitor.pollOnce(now: t(2))
        let writer = NSPasteboardWriter(pasteboard: pasteboard)
        let new = try await rig.monitor.writeBack(item: item, to: writer, now: t(3))

        XCTAssertEqual(new, pasteboard.changeCount)
        XCTAssertEqual(pasteboard.string(forType: .string), "original")
        XCTAssertNotNil(pasteboard.data(forType: NSPasteboard.PasteboardType(PBType.selfMarker)))
        let callsBefore = rig.reader.snapshotCalls
        await rig.monitor.pollOnce(now: t(4))
        XCTAssertEqual(rig.reader.snapshotCalls, callsBefore, "自己寫回的內容不會再被讀取")
        let order = await rig.store.items.compactMap(\.text)
        XCTAssertEqual(order, ["original", "something else"], "點選的條目被 bump 到最前面，且沒有新增重複條目")
    }

    func testWriteBackImageAndFilesRoundTripOnRealPasteboard() async throws {
        let rig = makeRig()
        await rig.monitor.start()
        externalCopy([(PBType.png, tinyPNG)])
        await rig.monitor.pollOnce(now: t(1))
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([NSURL(fileURLWithPath: "/Users/example/x.txt"), NSURL(fileURLWithPath: "/Users/example/y.txt")]))
        await rig.monitor.pollOnce(now: t(2))
        let items = await rig.store.items
        let image = try XCTUnwrap(items.first { $0.kind == .image })
        let files = try XCTUnwrap(items.first { $0.kind == .files })
        let writer = NSPasteboardWriter(pasteboard: pasteboard)

        _ = try await rig.monitor.writeBack(item: image, to: writer, now: t(3))
        XCTAssertEqual(pasteboard.data(forType: .png), tinyPNG)

        _ = try await rig.monitor.writeBack(item: files, to: writer, now: t(4))
        let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL]
        XCTAssertEqual(urls?.map(\.path), ["/Users/example/x.txt", "/Users/example/y.txt"])
        await rig.monitor.pollOnce(now: t(5))
        let count = await rig.store.items.count
        XCTAssertEqual(count, 2, "寫回不產生新條目")
    }

    // MARK: macOS 對具名剪貼簿的存取行為

    func testNamedPasteboardAccessBehaviorDoesNotRequireAPrompt() throws {
        guard #available(macOS 15.4, *) else { throw XCTSkip("accessBehavior 需要 macOS 15.4+") }
        // 標頭文件：具名（非 general）剪貼簿預設即「永遠允許」，程式化存取不會跳提示。
        // 因此這個整合測試無法驗證「系統剪貼簿」在 macOS 27 是否會跳提示（那需要碰系統剪貼簿，被禁止）。
        let behavior = pasteboard.accessBehavior
        XCTAssertTrue(behavior == .default || behavior == .alwaysAllow, "實際為 \(behavior.rawValue)")
    }
}
