import Foundation

/// 剪貼簿相關的 pasteboard 型別字串常數（測試以字面值鎖定，避免被無意間改掉）。
public enum ClipboardPasteboardType {
    /// 密碼管理員標記「機密內容」的型別（nspasteboard.org 慣例）。
    public static let concealed = "org.nspasteboard.ConcealedType"
    /// 標記「暫時性內容」的型別。
    public static let transient = "org.nspasteboard.TransientType"
    /// 標記「程式自動產生內容」的型別。
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    /// 1Password 的舊式標記型別（標示機密內容）。
    public static let onePassword = "com.agilebits.onepassword"
    /// 舊式「暫時性」標記型別（de.petermaurer；TextExpander、Textpander、Butler）。
    public static let petermaurerTransient = "de.petermaurer.TransientPasteboardType"
    /// 舊式「暫時性」標記型別（TypeIt4Me）。
    public static let typeIt4MeClipping = "com.typeit4me.clipping"
    /// 舊式「暫時性」標記型別（Typinator）。注意字串本身就含空白，原樣比對。
    public static let typinatorGenerator = "Pasteboard generator type"
    /// 本 app 寫回剪貼簿時附加的標記型別；資料為被點選條目的 UUID 字串。
    public static let selfMarker = "io.github.davidkong3804.DavidNook.self"
    /// 來源 App 的 bundle id（nspasteboard.org 慣例，部分 App 會提供）。
    public static let source = "org.nspasteboard.source"
    /// 檔案 URL。
    public static let fileURL = "public.file-url"
    /// PNG 圖片。
    public static let png = "public.png"
    /// TIFF 圖片。
    public static let tiff = "public.tiff"
    /// UTF-8 純文字。
    public static let utf8Text = "public.utf8-plain-text"

    /// 預設要略過（不記錄）的隱私標記型別集合。
    ///
    /// 來源：https://nspasteboard.org/ 。通用標記（Transient／Concealed／AutoGenerated）加上該頁
    /// 「Actions for Clipboard Historians」明列、歷史工具應支援的四個舊式專有型別。
    /// 刻意不含 `org.nspasteboard.source`（只是來源標記）與 `com.apple.is-remote-clipboard`
    /// （只表示內容來自其他裝置的 Handoff，頁面沒有要求略過，Universal Clipboard 的內容照常記錄）。
    public static let defaultIgnored: Set<String> = [
        concealed, transient, autoGenerated,
        petermaurerTransient, typeIt4MeClipping, typinatorGenerator, onePassword,
    ]
}

/// 剪貼簿某一時刻的快照：changeCount ＋ 型別清單 ＋「依型別取資料」。
/// 資料採「用到才讀」（lazy）：只看型別清單、changeCount、來源時不會讀取任何內容，
/// 因此被略過的（例如機密）剪貼簿內容完全不會被讀進記憶體。
public struct PasteboardSnapshot: Sendable {
    /// 取得快照當下的 changeCount。
    public let changeCount: Int
    /// 剪貼簿上所有宣告的型別（跨所有 pasteboard item 的聯集）。
    public let types: [String]
    private let sourceProvider: @Sendable () -> String?
    private let dataProvider: @Sendable (String) -> [Data]

    /// 以閉包延遲讀取資料與來源 App（真實 NSPasteboard 用）。
    public init(
        changeCount: Int,
        types: [String],
        sourceAppBundleIDProvider: @escaping @Sendable () -> String?,
        dataProvider: @escaping @Sendable (String) -> [Data]
    ) {
        self.changeCount = changeCount
        self.types = types
        self.sourceProvider = sourceAppBundleIDProvider
        self.dataProvider = dataProvider
    }

    /// 以閉包延遲讀取資料，來源 App 為固定值。
    public init(
        changeCount: Int,
        types: [String],
        sourceAppBundleID: String? = nil,
        dataProvider: @escaping @Sendable (String) -> [Data]
    ) {
        self.init(changeCount: changeCount, types: types, sourceAppBundleIDProvider: { sourceAppBundleID }, dataProvider: dataProvider)
    }

    /// 以現成資料建立快照（測試與 fake 用）。`data` 的每個陣列元素代表一個 pasteboard item 的資料。
    public init(
        changeCount: Int,
        types: [String],
        data: [String: [Data]] = [:],
        sourceAppBundleID: String? = nil
    ) {
        self.init(changeCount: changeCount, types: types, sourceAppBundleID: sourceAppBundleID) { type in data[type] ?? [] }
    }

    /// 來源 App 的 bundle id（若可得）。
    public var sourceAppBundleID: String? { sourceProvider() }

    /// 是否宣告了某型別（不分大小寫；只看型別清單，不讀資料）。
    public func hasType(_ type: String) -> Bool {
        let lowered = type.lowercased()
        return types.contains { $0.lowercased() == lowered }
    }

    /// 某型別在所有 pasteboard item 中的資料（例如一次複製多個檔案會有多筆 file URL）。
    public func allData(forType type: String) -> [Data] {
        dataProvider(type)
    }

    /// 某型別在第一個 pasteboard item 中的資料。
    public func data(forType type: String) -> Data? {
        allData(forType: type).first
    }
}

/// 抽象的「可讀取的剪貼簿」，讓 ClipboardMonitor 可用 fake 測試。
public protocol PasteboardReading: AnyObject, Sendable {
    /// 目前的 changeCount（便宜的呼叫，不讀內容）。
    var changeCount: Int { get }
    /// 取得目前內容的快照（資料延遲讀取）。
    func snapshot() -> PasteboardSnapshot
}

/// 要寫入剪貼簿的一種表示法（型別＋資料）。
public struct PasteboardRepresentation: Equatable, Sendable {
    /// pasteboard 型別字串。
    public let type: String
    /// 該型別的資料。
    public let data: Data

    /// 建立一筆表示法。
    public init(type: String, data: Data) {
        self.type = type
        self.data = data
    }
}

/// 抽象的「可寫入的剪貼簿」。
public protocol PasteboardWriting: AnyObject, Sendable {
    /// 清空剪貼簿並寫入多個 pasteboard item（每個 item 含多種表示法），回傳寫入完成後的 changeCount。
    func write(_ items: [[PasteboardRepresentation]]) -> Int
}
